version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: qairline-server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: qairline
    ports:
      - "3000:80"
    depends_on:
      - backend